name: Test Booking

on:
  workflow_dispatch:

jobs:
  test-booking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        
    - name: Run booking script
      env:
        BOOKING_URL: ${{ secrets.BOOKING_URL }}
        BOOKING_USERNAME: ${{ secrets.BOOKING_USERNAME }}
        PASSWORD: ${{ secrets.BOOKING_PASSWORD }}
      run: python test_access.py
