name: Test Booking

on:
  workflow_dispatch:

permissions:
  issues: write    # Add this permissions block

jobs:
  test-booking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        
    - name: Run booking script
      env:
        BOOKING_URL: ${{ secrets.BOOKING_URL }}
        BOOKING_USERNAME: ${{ secrets.BOOKING_USERNAME }}
        PASSWORD: ${{ secrets.BOOKING_PASSWORD }}      # Changed to match your secret name
      run: python test_access.py

    - name: Create Issue on Failure
      if: failure()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const status = fs.readFileSync(process.env.GITHUB_STEP_SUMMARY, 'utf8');
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Court Booking Failed',
            body: status
          });
          
    - name: Create Issue on Success
      if: success()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const status = fs.readFileSync(process.env.GITHUB_STEP_SUMMARY, 'utf8');
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Court Booking Successful',
            body: status
          });
